// Package updater provides secure, self-contained binary auto-update logic.
//
// Security guarantees:
//  1. All downloads happen over HTTPS only (net/http enforces this for https:// URLs).
//  2. SHA-256 of the downloaded binary is verified against the official
//     checksums.txt published alongside every GitHub release (generated by GoReleaser).
//  3. Binary replacement is atomic:
//     - Unix:    os.Rename (kernel-atomic; old inode stays open until process exits)
//     - Windows: staged swap via _update.bat (Windows locks running executables)
//
// The caller is responsible for initiating a restart after Download() returns nil.
package updater

import (
	"context"
	"crypto/sha256"
	"encoding/json"
	"fmt"
	"io"
	"log"
	"net/http"
	"os"
	"path/filepath"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"time"
)

// Config holds configuration for the Updater.
type Config struct {
	// CheckInterval is a duration string such as "24h" or "6h".
	CheckInterval string
	// ReleaseURL is the GitHub API endpoint that returns the latest release JSON.
	// Example: https://api.github.com/repos/owner/repo/releases/latest
	ReleaseURL string
}

// Release describes a newer GitHub release that has a binary asset for the
// current OS and architecture.
type Release struct {
	TagName     string
	PublishedAt time.Time
	AssetURL    string // download URL for the matching binary
	ChecksumURL string // download URL for checksums.txt
}

// Updater polls for new releases and applies them securely.
type Updater struct {
	cfg            Config
	currentVersion string
	mu             sync.RWMutex
	latest         *Release // last known newer release; nil = up-to-date
	client         *http.Client
}

// New creates an Updater. currentVersion should be a version string such as
// "0.1.0" or "v0.1.0" — the "v" prefix is normalised internally.
func New(cfg Config, currentVersion string) *Updater {
	return &Updater{
		cfg:            cfg,
		currentVersion: currentVersion,
		client: &http.Client{
			Timeout: 30 * time.Second,
		},
	}
}

// SetCurrentVersion updates the version string used for comparison.
// Call this after New() when the real version becomes available (e.g. after
// app.SetVersion is called from main.go).
func (u *Updater) SetCurrentVersion(v string) {
	u.mu.Lock()
	u.currentVersion = v
	u.mu.Unlock()
}

// Start begins the background polling loop.  It blocks until ctx is cancelled.
// Run it in a dedicated goroutine: go updater.Start(ctx).
func (u *Updater) Start(ctx context.Context) {
	interval := 24 * time.Hour
	if u.cfg.CheckInterval != "" {
		if d, err := time.ParseDuration(u.cfg.CheckInterval); err == nil && d > 0 {
			interval = d
		} else {
			log.Printf("[updater] invalid check_interval %q; using 24h", u.cfg.CheckInterval)
		}
	}

	u.mu.RLock()
	current := u.currentVersion
	u.mu.RUnlock()
	log.Printf("[updater] starting; interval=%s current=%s", interval, current)

	// Run an immediate check at startup so the user sees the notification quickly.
	u.runCheck()

	ticker := time.NewTicker(interval)
	defer ticker.Stop()

	for {
		select {
		case <-ctx.Done():
			log.Printf("[updater] stopped")
			return
		case <-ticker.C:
			u.runCheck()
		}
	}
}

// LatestRelease returns the last known newer release, or nil if the current
// version is up-to-date.  Safe for concurrent reads from the GUI goroutine.
func (u *Updater) LatestRelease() *Release {
	u.mu.RLock()
	defer u.mu.RUnlock()
	return u.latest
}

// CheckNow performs an immediate check against the GitHub releases API.
// Returns (*Release, nil) when a newer version is available, (nil, nil) when
// up-to-date, or (nil, error) on failure.
func (u *Updater) CheckNow() (*Release, error) {
	if u.cfg.ReleaseURL == "" {
		return nil, fmt.Errorf("release_url is not configured")
	}

	req, err := http.NewRequest(http.MethodGet, u.cfg.ReleaseURL, nil)
	if err != nil {
		return nil, fmt.Errorf("build request: %w", err)
	}
	req.Header.Set("Accept", "application/vnd.github+json")
	req.Header.Set("User-Agent", "soholink-updater/1")

	resp, err := u.client.Do(req)
	if err != nil {
		return nil, fmt.Errorf("GET %s: %w", u.cfg.ReleaseURL, err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("GitHub API returned HTTP %d", resp.StatusCode)
	}

	var gh struct {
		TagName     string    `json:"tag_name"`
		PublishedAt time.Time `json:"published_at"`
		Assets      []struct {
			Name               string `json:"name"`
			BrowserDownloadURL string `json:"browser_download_url"`
		} `json:"assets"`
	}
	if err := json.NewDecoder(resp.Body).Decode(&gh); err != nil {
		return nil, fmt.Errorf("decode response: %w", err)
	}

	u.mu.RLock()
	current := u.currentVersion
	u.mu.RUnlock()

	newer, err := isNewerSemver(gh.TagName, current)
	if err != nil {
		return nil, fmt.Errorf("version compare: %w", err)
	}
	if !newer {
		return nil, nil
	}

	// Find the binary asset and checksums.txt for the current OS+arch.
	goos := runtime.GOOS
	goarch := runtime.GOARCH
	var assetURL, checksumURL string

	for _, a := range gh.Assets {
		nameLower := strings.ToLower(a.Name)
		if a.Name == "checksums.txt" {
			checksumURL = a.BrowserDownloadURL
			continue
		}
		if strings.Contains(nameLower, goos) && strings.Contains(nameLower, goarch) {
			switch {
			case goos == "windows" && strings.HasSuffix(nameLower, ".exe"):
				assetURL = a.BrowserDownloadURL
			case goos == "windows" && strings.HasSuffix(nameLower, ".zip"):
				if assetURL == "" {
					assetURL = a.BrowserDownloadURL
				}
			case goos != "windows" && strings.HasSuffix(nameLower, ".tar.gz"):
				assetURL = a.BrowserDownloadURL
			}
		}
	}

	if assetURL == "" {
		return nil, fmt.Errorf("no binary asset for %s/%s in release %s", goos, goarch, gh.TagName)
	}
	if checksumURL == "" {
		return nil, fmt.Errorf("no checksums.txt in release %s", gh.TagName)
	}

	return &Release{
		TagName:     gh.TagName,
		PublishedAt: gh.PublishedAt,
		AssetURL:    assetURL,
		ChecksumURL: checksumURL,
	}, nil
}

// Download downloads, verifies, and atomically installs the given release.
//
// On Unix it calls os.Rename for an in-place atomic swap.
// On Windows it stages soholink_new.exe + _update.bat; the swap completes on
// the next restart.
//
// Returns nil on success.  The caller should prompt the user to restart.
func (u *Updater) Download(ctx context.Context, rel *Release) error {
	// Step 1: Download checksums.txt.
	log.Printf("[updater] downloading checksums for %s", rel.TagName)
	checksums, err := u.fetchText(ctx, rel.ChecksumURL)
	if err != nil {
		return fmt.Errorf("download checksums: %w", err)
	}

	// Step 2: Download binary to a temp file.
	log.Printf("[updater] downloading binary: %s", rel.AssetURL)
	tmp, err := os.CreateTemp("", "soholink-update-*")
	if err != nil {
		return fmt.Errorf("create temp file: %w", err)
	}
	tmpPath := tmp.Name()
	defer func() {
		tmp.Close()
		// Best-effort cleanup on failure; on success the file is moved/renamed.
		os.Remove(tmpPath)
	}()

	if err := u.downloadTo(ctx, rel.AssetURL, tmp); err != nil {
		return fmt.Errorf("download binary: %w", err)
	}
	tmp.Close()

	// Step 3: SHA-256 verification.
	log.Printf("[updater] verifying SHA-256...")
	got, err := sha256File(tmpPath)
	if err != nil {
		return fmt.Errorf("hash temp file: %w", err)
	}
	want, err := findChecksum(checksums, rel.AssetURL)
	if err != nil {
		return fmt.Errorf("checksum lookup: %w", err)
	}
	if !strings.EqualFold(got, want) {
		return fmt.Errorf("checksum MISMATCH: got %s, want %s — aborting", got, want)
	}
	log.Printf("[updater] SHA-256 OK (%s...)", got[:16])

	// Step 4: Install.
	execPath, err := os.Executable()
	if err != nil {
		return fmt.Errorf("resolve executable path: %w", err)
	}

	if runtime.GOOS == "windows" {
		return u.installWindows(tmpPath, execPath)
	}
	return u.installUnix(tmpPath, execPath)
}

// ── private helpers ───────────────────────────────────────────────────────────

func (u *Updater) runCheck() {
	rel, err := u.CheckNow()
	if err != nil {
		log.Printf("[updater] check failed: %v", err)
		return
	}
	u.mu.Lock()
	u.latest = rel
	u.mu.Unlock()

	if rel != nil {
		log.Printf("[updater] update available: %s (published %s)", rel.TagName, rel.PublishedAt.Format("2006-01-02"))
	} else {
		u.mu.RLock()
		current := u.currentVersion
		u.mu.RUnlock()
		log.Printf("[updater] up-to-date (%s)", current)
	}
}

func (u *Updater) fetchText(ctx context.Context, url string) (string, error) {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return "", err
	}
	resp, err := u.client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()
	b, err := io.ReadAll(io.LimitReader(resp.Body, 1<<20)) // 1 MiB cap
	return string(b), err
}

func (u *Updater) downloadTo(ctx context.Context, url string, dst *os.File) error {
	req, err := http.NewRequestWithContext(ctx, http.MethodGet, url, nil)
	if err != nil {
		return err
	}
	resp, err := u.client.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("HTTP %d from %s", resp.StatusCode, url)
	}
	_, err = io.Copy(dst, resp.Body)
	return err
}

// installUnix atomically replaces the running executable.
// The kernel keeps the old inode open until all file descriptors are closed,
// so os.Rename is safe even while the binary is running.
func (u *Updater) installUnix(tmpPath, execPath string) error {
	if err := os.Chmod(tmpPath, 0o755); err != nil {
		return fmt.Errorf("chmod: %w", err)
	}
	if err := os.Rename(tmpPath, execPath); err != nil {
		return fmt.Errorf("rename: %w", err)
	}
	log.Printf("[updater] installed to %s — restart to apply", execPath)
	return nil
}

// installWindows stages the new binary as soholink_new.exe and writes
// _update.bat, which performs the swap after the process exits.
// Windows exclusively locks running executables, so an in-place rename
// is impossible while the process is alive.
func (u *Updater) installWindows(tmpPath, execPath string) error {
	dir := filepath.Dir(execPath)
	newExe := filepath.Join(dir, "soholink_new.exe")
	batPath := filepath.Join(dir, "_update.bat")

	// Move temp download to soholink_new.exe.
	if err := os.Rename(tmpPath, newExe); err != nil {
		// Rename across volumes fails; fall back to copy.
		if copyErr := copyFile(tmpPath, newExe); copyErr != nil {
			return fmt.Errorf("stage new binary: %w", copyErr)
		}
		os.Remove(tmpPath)
	}

	// Write self-deleting batch file.
	bat := fmt.Sprintf(`@echo off
:WAIT
tasklist /FI "IMAGENAME eq soholink.exe" 2>NUL | find /I /N "soholink.exe">NUL
if NOT ERRORLEVEL 1 (
    timeout /T 2 /NOBREAK >NUL
    goto WAIT
)
move /Y "%s" "%s"
start "" "%s"
del "%%~f0"
`, newExe, execPath, execPath)

	if err := os.WriteFile(batPath, []byte(bat), 0o644); err != nil {
		return fmt.Errorf("write update batch: %w", err)
	}

	log.Printf("[updater] update staged; restart SoHoLINK to apply (or run %s)", batPath)
	return nil
}

func sha256File(path string) (string, error) {
	f, err := os.Open(path)
	if err != nil {
		return "", err
	}
	defer f.Close()
	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return "", err
	}
	return fmt.Sprintf("%x", h.Sum(nil)), nil
}

// findChecksum extracts the expected hex-SHA256 for the asset whose filename
// matches the last path component of assetURL.
// GoReleaser checksums.txt format: "<sha256hex>  <filename>"
func findChecksum(checksums, assetURL string) (string, error) {
	parts := strings.Split(assetURL, "/")
	filename := parts[len(parts)-1]

	for _, line := range strings.Split(checksums, "\n") {
		line = strings.TrimSpace(line)
		if strings.HasSuffix(line, " "+filename) || strings.HasSuffix(line, "\t"+filename) {
			fields := strings.Fields(line)
			if len(fields) >= 1 {
				return fields[0], nil
			}
		}
	}
	return "", fmt.Errorf("no checksum entry for %q in checksums.txt", filename)
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	defer out.Close()
	_, err = io.Copy(out, in)
	return err
}

// isNewerSemver returns true when latestTag is strictly newer than currentTag.
// Both tags are normalised to strip a leading "v".
// Only the first three numeric components (major.minor.patch) are compared.
func isNewerSemver(latestTag, currentTag string) (bool, error) {
	la := parseSemver(latestTag)
	cu := parseSemver(currentTag)
	if la == nil || cu == nil {
		return false, fmt.Errorf("cannot parse semver: latest=%q current=%q", latestTag, currentTag)
	}
	for i := 0; i < 3; i++ {
		if la[i] > cu[i] {
			return true, nil
		}
		if la[i] < cu[i] {
			return false, nil
		}
	}
	return false, nil // equal
}

// parseSemver strips a leading "v" and splits "major.minor.patch" into ints.
// Returns nil if the string is not a valid semver.
func parseSemver(v string) []int {
	v = strings.TrimPrefix(v, "v")
	parts := strings.SplitN(v, ".", 3)
	if len(parts) < 3 {
		return nil
	}
	nums := make([]int, 3)
	for i, p := range parts {
		// Strip any pre-release/build suffix (e.g. "1-beta" → 1).
		p = strings.FieldsFunc(p, func(r rune) bool { return r == '-' || r == '+' })[0]
		n, err := strconv.Atoi(p)
		if err != nil {
			return nil
		}
		nums[i] = n
	}
	return nums
}
